version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/python:3.7.2"
    working_directory: ~/repo
    environment:
      VIRTUALENV_DIR: "~/virtualenv"
      # Don't install various StackStorm dependencies which are already
      # installed by CI again in the various check scripts
      ST2_INSTALL_DEPS: "0"

    steps:
      - checkout
      - restore_cache:
            key: v1-dependency-cache-py37-{{ checksum "requirements.txt" }}
      - run:
          name: create venv and install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: v1-dependency-cache-py37-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip
            - ~/.apt-cache
  deploy:
    docker:
      - image: "circleci/python:3.7.2"
    working_directory: ~/repo
    environment:
      VIRTUALENV_DIR: "~/virtualenv"
      # Don't install various StackStorm dependencies which are already
      # installed by CI again in the various check scripts
      ST2_INSTALL_DEPS: "0"

    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-py37-{{ checksum "requirements.txt" }}
      - attach_workspace:
          at: /
      - run:
          name: Deployment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 setup.py sdist bdist_wheel
            ls -lrt;
            mkdir /tmp/artifacts;
            cp -R build/ /tmp/artifacts;
            cp -R dist/ /tmp/artifacts;
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build # only deploy once build job has completed
          filters:
            branches:
              only: main